### ISSUE TITLE
clean up dependencies?

### ISSUE THREAD

**Issue by mathause** [conda-forge/climpred-feedstock#26]
### Comment:

I had a look at you meta.yaml file and noticed some dependencies that might be good to clean up?

- You have cftime dependencies in the main repo that are missing here (might be in the stack, though)

- You depend on ipython - I don't think that's necessary?
   https://github.com/conda-forge/climpred-feedstock/blob/d8e8cc271149eb3798f29890cae6a234d0ab75b1/recipe/meta.yaml#L32

- You have an upper pin for xarray. Is there a good reason for this? Would be nice if you can get rid of that.
https://github.com/conda-forge/climpred-feedstock/blob/d8e8cc271149eb3798f29890cae6a234d0ab75b1/recipe/meta.yaml#L41

- You have different pins on xclim, here and on pangeo-data/climpred:
   - you have an upper pin
https://github.com/pangeo-data/climpred/blob/1424e89e9bdf3eb1ae47d581be2953ede0b98996/setup.py#L31
  - and a lower pin
https://github.com/conda-forge/climpred-feedstock/blob/d8e8cc271149eb3798f29890cae6a234d0ab75b1/recipe/meta.yaml#L42

pining @Zeitsperre & @aaronspring (I wasn't sure if I should report here or in pangeo-data/climpred)

**Comment by aaronspring** [comment]
Here's a great place to discuss. Thanks for starting this discussion. 

Right now I don't remember why I pinned xarray. 

Please feel free to add PRs and try to simplify dependencies. I won't have time to dig deep myself.

**Comment by aaronspring** [comment]
ipython isn't used by climpred since https://github.com/pangeo-data/climpred/commit/8ffa68e4ef4f5a94255513980cd46ff317e3c6b7

**Comment by aaronspring** [comment]
About the xarray pin, I might have been to lazy to fix the underlying new error popping up and went for the bad fix 🙈

**Comment by aaronspring** [comment]
xclim is an optional dependency when installing with pip. Unsure whether that's possible with conda and therefore just added

**Comment by Zeitsperre** [comment]
That upper pin on xclim was news to me. It might be the source of a few issues I've seen elsewhere! Thanks for pointing that out.

@aaronspring I think the pin on xarray was due to the breakage that happened when Pandas v2.0 was released. This might also explain the pin on xclim as well (everything was broken in that Pandas release). I'm not sure if there were major changes needed for Climpred to work with Pandas v2.0; Maybe we should open the pins and see what breaks?

I know that you can set optional dependency versions for packages on conda-forge (i.e.: if the package is found in the environment, it must be `>=vX.Y.Z,<vA.B.C`). Worst case scenario, we could use that to solve things in the meantime?

**Comment by aaronspring** [comment]
Now with an updated climpred and even xskillscore repo, we can release a new conda version
